Add instruction for install Feast on IKS using Kustomize (Draft)
feast-dev/feast pull request #1534
Opened 2021-05-05 07:59 UTC by tedhtchang

Signed-off-by: ted chang <htchang@us.ibm.com>

Add instruction for install Feast on IKS and OpenShift on IBM Cloud using Kustomize.
Remove instruction for install Feast on IKS with helm
Update urls in README, CONTRIBUTOR, and SUMMARY md files.

**Does this PR introduce a user-facing change?**:
NONE

2021-05-05 08:10 UTC, tedhtchang commented
/cc @pvaneck @animeshsingh

2021-05-06 03:28 UTC, pvaneck requested changes

2021-05-06 03:28 UTC, pvaneck commented on docs/feast-on-kubernetes/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
> +By default, in OpenShift, all pods or containers will use the [Restricted SCC](https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html) which preve
```suggestion
By default, in OpenShift, all pods or containers will use the [Restricted SCC](https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html) which limits the UIDs pods can run with, causing the Feast installation to fail. To overcome this, you can allow Feast pods to run with any UID by executing the following:
```

2021-05-06 03:28 UTC, pvaneck commented on docs/feast-on-kubernetes/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
> +You may optionally enable the Feast Jupyter which contains code examples to demonstrate Feast. Some examples require Kafka to stream real time features to the Feast online serving. To enable, edit th
add "component" after Jupyter.

2021-05-08 05:50 UTC, tedhtchang commented on docs/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
> -# IBM Cloud Kubernetes Service \(IKS\) \(with Helm\)
This one will be replaced by the ibm-cloud-iks-with-kustomize.md.

2021-05-13 00:34 UTC, woop commented
@tedhtchang we're not reviewing anything here yet since it's a draft. Let us know if you want us to look at anything.

2021-05-14 20:46 UTC, animeshsingh commented on docs/feast-on-kubernetes/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
> +### Security Context Constraint Setup
```suggestion
### Security Context Constraint Setup (OpenShift only)
```

2021-05-14 20:46 UTC, animeshsingh commented on docs/feast-on-kubernetes/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
> +## 4. Use Feast Jupyter to connect to Feast
```suggestion
## 4. Use Feast Jupyter Notebook Server to connect to Feast
```

2021-05-17 18:00 UTC, tedhtchang commented
@woop This PR is ready to review. Please take a look. Thanks.

2021-05-18 21:51 UTC, woop commented
/lgtm

2021-05-18 21:52 UTC, merged