Fix #2297 Materialize bug with RedisCluster
feast-dev/feast pull request #2311
Opened 2022-02-15 17:53 UTC by kevjumba

Signed-off-by: Kevin Zhang <kzhang@tecton.ai>

**What this PR does / why we need it**:
Broken materialization script for feast 0.18.0. Refer to issue #2297.
Issue was that there are 2 versions of the python redis cluster package redis-py-cluster and redis-py. redis-py only recently added a new version of RedisCluster and our api was using the redis-py-cluster api that passes dictionary of host:port pairs while redis-py implementation requires ClusterNodes instead.

**Which issue(s) this PR fixes**:

Fixes #2297

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-02-15 18:02 UTC, felixwang9817 requested changes

2022-02-15 18:05 UTC, kevjumba commented on sdk/python/feast/infra/online_stores/redis.py
> +                ]
Oh oops, accidentally removed that when I was copy pasting. thx

2022-02-17 01:23 UTC, felixwang9817 approved these changes
/lgtm

2022-02-17 01:25 UTC, kevjumba commented
@adchia PTAL!

2022-02-17 17:57 UTC, adchia approved these changes
/lgtm

2022-02-17 17:57 UTC, merged