Implements connection pool for postgres online store
feast-dev/feast pull request #3633
Opened 2023-05-18 12:47 UTC by Natan16

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

2023-05-18 13:22 UTC, avelino requested changes

2023-05-18 13:22 UTC, avelino commented on sdk/python/feast/infra/online_stores/contrib/postgres.py
> +from feast.infra.utils.postgres.connection_utils import _get_connection_pool
We are forcing `pool` connection **by default**, we should leave it configurable by the user (he should choose the connection time that will be used), force `pool` connection in small project will be *"expensive"* (unnecessary resource usage).

**My suggestion** would be to let the user **choose** the connection type, **not `pool`** by *default* and the projects that need pool define it as pool

2023-05-18 13:22 UTC, avelino commented on sdk/python/feast/infra/utils/postgres/postgres_config.py
> +    max_conn: int = 10
create a connection definition variable that will be used from `_get_conn()`

**e.g:**
```py
type_conn: str = "normal" # or "pool"
```

2023-05-22 12:13 UTC, avelino commented
> Ok, I added back the possibility to use a single connection, now with the parameter `keepalives_idle` in case the database is configured to drop idle connections. 0 uses the system default.

@Natan16 great, I think it is important to write a unit test to validate the behavior that was implemented

@adchia are we going in the best direction for the project?

2023-06-04 01:15 UTC, felixwang9817 approved these changes
/lgtm

2023-06-04 03:00 UTC, merged