feat: Make RegistryServer writable
feast-dev/feast pull request #4231
Opened 2024-05-24 21:38 UTC by tokoko

# What this PR does / why we need it:
This PR add apply/delete endpoints to the grpc registry server, also makes necessary changes in `remote` registry that call those endpoints. server/remote specific tests have been deleted in favor of `test_universal_registry.py`.

# Which issue(s) this PR fixes:
Fixes #4216

2024-05-26 01:36 UTC, franciscojavierarceo commented on sdk/python/tests/integration/registration/test_feature_store.py
> -import os
There's a lot being deleted here. Can you update the PR notes to explain why? I'm not fully familiar with the usage of all of these tests so I'd like to make sure I understand the implications of removing all of these tests (along with the other files).

2024-05-26 01:36 UTC, franciscojavierarceo commented on sdk/python/tests/integration/registration/test_universal_registry.py
> -@pytest.mark.parametrize(
Same here

2024-05-26 01:36 UTC, franciscojavierarceo commented on sdk/python/tests/unit/infra/registry/test_remote.py
> -import assertpy
Same here

2024-05-26 01:37 UTC, franciscojavierarceo commented on sdk/python/tests/unit/test_registry_server.py
> -import assertpy
Same here

2024-05-26 01:38 UTC, franciscojavierarceo requested changes
Can you add more details to the PR notes for this? Looks like we're removing a lot of tests and I'd like to make sure I understand the consequences of doing so as I'm not familiar with the usage of those tests.

2024-05-26 04:25 UTC, tokoko commented
Updated the PR description, let me know if it needs more clarity.

2024-05-27 10:31 UTC, franciscojavierarceo commented
Thanks for updating the PR description. 

Can you separate the removal of the tests into another PR? It'd be much cleaner in case we need to revert it.

2024-05-27 16:15 UTC, tokoko commented
@franciscojavierarceo cut down on the scope of the PR, reverted all test removals.

2024-05-27 16:31 UTC, franciscojavierarceo approved these changes
thank you!

2024-05-27 16:31 UTC, merged