chore: Remove Rockset from feast
feast-dev/feast pull request #4434
Opened 2024-08-21 20:37 UTC by tokoko

Fixes #4404

2024-08-21 20:52 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.infra.feature_servers.aws_lambda.rst
> -feast.infra.feature\_servers.aws\_lambda package
Do we need to remove this?

2024-08-21 20:53 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.infra.feature_servers.gcp_cloudrun.rst
> -feast.infra.feature\_servers.gcp\_cloudrun package
Why remove this?

2024-08-21 20:53 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.infra.materialization.contrib.bytewax.rst
> -feast.infra.materialization.contrib.bytewax package
Why remove this?

2024-08-21 20:53 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.infra.materialization.lambda.rst
> -feast.infra.materialization.lambda package
Why remove this?

2024-08-21 20:53 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.infra.registry.contrib.postgres.rst
> -feast.infra.registry.contrib.postgres package
Why remove this?

2024-08-21 20:54 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.infra.registry_stores.rst
> -feast.infra.registry\_stores package
Why remove this?

2024-08-21 20:54 UTC, franciscojavierarceo commented on sdk/python/docs/source/feast.rst
> -feast.prova module
Why remove this?

2024-08-21 20:56 UTC, franciscojavierarceo requested changes
Nice! Think you may have deleted some extra stuff in some cases. Mind confirming?

2024-08-21 21:08 UTC, tokoko commented
I simply regenerated sphinx docs. Those files should have been deleted in previous PRs when those modules were deleted, but looks like they stuck around. I think the problem is that our sphinx regeneration command in Makefile only updates existing files, but doesn't delete already existing ones. I'll try to fix that later as well.

2024-08-22 10:28 UTC, franciscojavierarceo commented
Got it that makes sense.

2024-08-26 10:22 UTC, tokoko commented
@franciscojavierarceo are you waiting on any changes for this to be merged?

2024-08-26 10:30 UTC, franciscojavierarceo approved these changes

2024-08-26 10:30 UTC, merged