fix: Feast Operator updated the kustomize version to v5.5.0
feast-dev/feast pull request #4805
Opened 2024-12-02 23:36 UTC by redhatHameed

# What this PR does / why we need it:

 Faced issue on a Mac M3,  was unable to run `make install`. Updating kustomize to the latest version (v5.5.0)resolved the problem.

# Which issue(s) this PR fixes:

# Misc

2024-12-03 01:46 UTC, redhatHameed commented
@tchughesiv @lokeshrangineni as discussed I was facing issue while `make install` for operator

2024-12-03 13:59 UTC, dmartinol approved these changes

2024-12-04 17:27 UTC, tchughesiv requested changes
this should not be merged as it requires a newer go version. 
```shell
Downloading sigs.k8s.io/kustomize/kustomize/v5@v5.5.0
go: downloading sigs.k8s.io/kustomize/kustomize/v5 v5.5.0
go: sigs.k8s.io/kustomize/kustomize/v5@v5.5.0: sigs.k8s.io/kustomize/kustomize/v5@v5.5.0 requires go >= 1.22.7 (running go 1.21.13; GOTOOLCHAIN=local)
make: *** [/Users/tohughes/workspace/feast/infra/feast-operator/bin/kustomize-v5.5.0] Error 1
```
instead please get setup your local env to use go1.21 as is expressed in the contrib prereqs
https://github.com/feast-dev/feast/blob/2c5a6b554cf6170b2590f32124cd7b84121cb864/infra/feast-operator/README.md?plain=1#L110-L111

2024-12-04 17:28 UTC, tchughesiv commented
let's close this PR, its an environmental issue and would break several things

2024-12-04 17:29 UTC, closed without merging